name = "portal-excursiones"
main = "worker.js"
compatibility_date = "2024-05-22"

[site]
bucket = "./"  # Si estás sirviendo archivos estáticos (como HTML, CSS, imágenes)

[build]
command = ""

[env.production]
workers_dev = true
